/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conn;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author stroe
 */
public class VizualizareProduse extends javax.swing.JFrame {
    Connection conn=null;
    OraclePreparedStatement pst=null,pst1=null;
    OracleResultSet rs=null;
    /**
     * Creates new form VizualizareProduse
     */
    public VizualizareProduse() {
       super("Vizualizare Produse Și Gestiune");
        initComponents();
        conn=JavaConnectDB.ConnecrDB();
       Show_Products_In_JTable();
    }
    int pos =0;
    
    //resetare campuri 
     public void clearFields(){
        cod.setText(null);
        denumire.setText(null);
        pret.setText(null);
    }
     
     //Verificati campurile de intrare
    
    public boolean checkInputs(){
        if(        
                    cod.getText()==null
                || denumire.getText()==null
                || pret.getText()==null
                ){
                    return false;
              }else{
                    try{
                        Float.parseFloat(pret.getText());
                        return true;
                    }catch(Exception ex){
                        return false;
                    }
        }   
        
    }
    
    
    
    //Afisarea datelor in Tabla
     //         1 -- Umplerea listei cu datele
    
        public ArrayList<Produse> getProduseList(){
        
            ArrayList<Produse> produseList = new ArrayList<Produse>();
            String query = "select * from produs";
            try {
            Statement state=conn.createStatement();
            ResultSet rs=state.executeQuery(query);
            Produse product;
            
            while(rs.next()){
                product=new Produse(rs.getInt("CODPRODUS"),rs.getString("DENPRODUS"),rs.getString("PRETREFERINTA"));
                produseList.add(product);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(VizualizareProduse.class.getName()).log(Level.SEVERE, null, ex);
        }
        return    produseList;
     
        }
     
     //         2 -- Popularea Tablei
     public void Show_Products_In_JTable(){
         ArrayList<Produse> list = getProduseList();
         DefaultTableModel model = (DefaultTableModel)produse.getModel();
        
         
         model.setRowCount(0);
         Object[] row = new Object[3];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getcod();
            row[1] = list.get(i).getdenumire();
            row[2] = list.get(i).getpret();
            
            model.addRow(row);
        }  
         
     }
     
     
      public void ShowItem(int index){
         cod.setText(Integer.toString(getProduseList().get(index).getcod()));
         denumire.setText(getProduseList().get(index).getdenumire());
         pret.setText(getProduseList().get(index).getpret());
          
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pret = new javax.swing.JTextField();
        denumire = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        produse = new javax.swing.JTable();
        urmatorul = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        inapoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        actualizati = new javax.swing.JButton();
        sterge = new javax.swing.JButton();
        cod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cod Produs");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Denumire Produs");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pret Referinta");

        pret.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pret.setPreferredSize(new java.awt.Dimension(6, 25));

        denumire.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        denumire.setPreferredSize(new java.awt.Dimension(6, 25));

        produse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Produs", "Denumire Produs", "Pret Referinta"
            }
        ));
        produse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(produse);

        urmatorul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        urmatorul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Forward_20px.png"))); // NOI18N
        urmatorul.setText("Urmatorul");
        urmatorul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urmatorulActionPerformed(evt);
            }
        });

        anterior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Back_20px.png"))); // NOI18N
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        inapoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inapoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Back_20px.png"))); // NOI18N
        inapoi.setText("Inapoi");
        inapoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inapoiActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 204));
        jLabel12.setText("Vizualizare Produse Și Gestiune");

        actualizati.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actualizati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Update_20px.png"))); // NOI18N
        actualizati.setText("Actualizare");
        actualizati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizatiActionPerformed(evt);
            }
        });

        sterge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sterge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Delete_20px.png"))); // NOI18N
        sterge.setText("Ștergere");
        sterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stergeActionPerformed(evt);
            }
        });

        cod.setEditable(false);
        cod.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inapoi)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(actualizati)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sterge)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(500, 500, 500))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(urmatorul)
                                .addGap(253, 253, 253))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(denumire, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(pret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(denumire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inapoi)
                    .addComponent(actualizati)
                    .addComponent(sterge)
                    .addComponent(urmatorul)
                    .addComponent(anterior))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1209, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void produseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produseMouseClicked
        // TODO add your handling code here:
        int index=produse.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_produseMouseClicked

    private void urmatorulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urmatorulActionPerformed
        // TODO add your handling code here:
        pos++;

        if(pos>=getProduseList().size()){
            pos=getProduseList().size()-1;
        }
        ShowItem(pos);
    }//GEN-LAST:event_urmatorulActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        pos--;
        if(pos<0){
            pos=0;
        }
        ShowItem(pos);
    }//GEN-LAST:event_anteriorActionPerformed

    private void inapoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inapoiActionPerformed
        // TODO add your handling code here:
        this.hide();
        Meniu frm=new Meniu();
        frm.setVisible(true);
    }//GEN-LAST:event_inapoiActionPerformed

    private void actualizatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizatiActionPerformed
        // TODO add your handling code here:
        if(checkInputs()){
            String UptadeQuery=null;
             pst=null;
           
                try {
                    UptadeQuery="UPDATE produs SET DENPRODUS=?, PRETREFERINTA=? where CODPRODUS=?";
                    pst=(OraclePreparedStatement) conn.prepareStatement(UptadeQuery);
                    pst.setString(1, denumire.getText());
                    pst.setString(2, pret.getText());
                    pst.setString(3, cod.getText());
                    pst.executeUpdate();
                    Show_Products_In_JTable();
                    JOptionPane.showMessageDialog(null, "Produsul A Fost Actualizata!");
                    clearFields();
                } catch (Exception ex) {
                    Logger.getLogger(AdaugatiProduse.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else
        {
            JOptionPane.showMessageDialog(null,"Unul sau mau multe câmpuri sunt goale!");
        
    }//GEN-LAST:event_actualizatiActionPerformed
    }
    
    private void stergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stergeActionPerformed
        // TODO add your handling code here:
        
        if(!cod.getText().equals(""))
        {
            try {
              pst1=(OraclePreparedStatement) conn.prepareStatement("DELETE FROM facturat WHERE CODPRODUS=? ");
             int id1=Integer.parseInt(cod.getText());
              pst1.setInt(1, id1);
              pst1.executeUpdate();
              pst=(OraclePreparedStatement) conn.prepareStatement("DELETE FROM produs WHERE CODPRODUS=? ");
                int id=Integer.parseInt(cod.getText());
                pst.setInt(1, id);
                pst.executeUpdate();
                Show_Products_In_JTable();
                JOptionPane.showMessageDialog(null,"Produsul a fost stersă!");
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(AdaugatiProduse.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Produsul nu a fost stearsă!");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Produsul nu a fost stearsă : Nu se șterge id-ul!");
        }

    }//GEN-LAST:event_stergeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VizualizareProduse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VizualizareProduse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VizualizareProduse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VizualizareProduse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VizualizareProduse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizati;
    private javax.swing.JButton anterior;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField denumire;
    private javax.swing.JButton inapoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pret;
    private javax.swing.JTable produse;
    private javax.swing.JButton sterge;
    private javax.swing.JButton urmatorul;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Produse> getproduseList() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
