/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conn;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author stroe
 */
public class VizualizareClienti extends javax.swing.JFrame {
Connection conn=null;
    OraclePreparedStatement pst=null,pst1=null,pst2=null;
    OracleResultSet rs=null;
    /**
     * Creates new form VizualizareClienti
     */
    public VizualizareClienti() {
        super("Vizualizare Produse Și Gestiune");
        initComponents();
        conn=JavaConnectDB.ConnecrDB();
       Show_Products_In_JTable();
    }
    
    
    
    int pos =0;
    
    //resetare campuri 
     public void clearFields(){
        cod.setText(null);
        nume.setText(null);
        telefon.setText(null);
        strada.setText(null);
        numar.setText(null);
        tip.setText(null);
    }
     
     //Verificati campurile de intrare
    
    public boolean checkInputs(){
        if(        
                    cod.getText()==null
                || nume.getText()==null
                || telefon.getText()==null
                || strada.getText()==null
                || numar.getText()==null
                ){
                    return false;
              }else{
                    try{
                        Float.parseFloat(numar.getText());
                        return true;
                    }catch(Exception ex){
                        return false;
                    }
        }   
        
    }
    
     //Afisarea datelor in Tabla
     //         1 -- Umplerea listei cu datele
    
        public ArrayList<Clienti> getClientiList(){
        
            ArrayList<Clienti> clientiList = new ArrayList<Clienti>();
            String query = "select * from client";
            try {
            Statement state=conn.createStatement();
            ResultSet rs=state.executeQuery(query);
            Clienti product;
            
            while(rs.next()){
                product=new Clienti(rs.getInt("CODCLIENT"),rs.getString("NUME"),rs.getString("TELEFON"),rs.getString("STRADA"),rs.getString("NUMARUL"),rs.getString("TIPCLIENT"));
                clientiList.add(product);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(VizualizareProduse.class.getName()).log(Level.SEVERE, null, ex);
        }
        return    clientiList;
     
        }
     
     //         2 -- Popularea Tablei
     public void Show_Products_In_JTable(){
         ArrayList<Clienti> list = getClientiList();
         DefaultTableModel model = (DefaultTableModel)clienti.getModel();
        
         
         model.setRowCount(0);
         Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getcod();
            row[1] = list.get(i).getnume();
            row[2] = list.get(i).gettelefon();
            row[3] = list.get(i).getstrada();
            row[4] = list.get(i).getnumar();
            row[5] = list.get(i).gettip();
            
            model.addRow(row);
        }  
         
     }
     
     
      public void ShowItem(int index){
         cod.setText(Integer.toString(getClientiList().get(index).getcod()));
         nume.setText(getClientiList().get(index).getnume());
         telefon.setText(getClientiList().get(index).gettelefon());
         strada.setText(getClientiList().get(index).getstrada());
         numar.setText(getClientiList().get(index).getnumar());
         tip.setText(getClientiList().get(index).gettip());
     }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numar = new javax.swing.JTextField();
        strada = new javax.swing.JTextField();
        telefon = new javax.swing.JTextField();
        nume = new javax.swing.JTextField();
        cod = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienti = new javax.swing.JTable();
        urmatorul = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        inapoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        actualizati = new javax.swing.JButton();
        sterge = new javax.swing.JButton();
        tip = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cod Client");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nume");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefon");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Strada");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Numarul");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tip Client");

        numar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        numar.setPreferredSize(new java.awt.Dimension(6, 25));

        strada.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        strada.setPreferredSize(new java.awt.Dimension(6, 25));

        telefon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        telefon.setPreferredSize(new java.awt.Dimension(6, 25));

        nume.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nume.setPreferredSize(new java.awt.Dimension(6, 25));

        cod.setEditable(false);
        cod.setBackground(new java.awt.Color(204, 204, 204));
        cod.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cod.setEnabled(false);
        cod.setPreferredSize(new java.awt.Dimension(6, 25));

        clienti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Client", "Nume", "Telefon", "Strada", "Numarul", "Tip Client"
            }
        ));
        clienti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(clienti);

        urmatorul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        urmatorul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Forward_20px.png"))); // NOI18N
        urmatorul.setText("Urmatorul");
        urmatorul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urmatorulActionPerformed(evt);
            }
        });

        anterior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Back_20px.png"))); // NOI18N
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        inapoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inapoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Back_20px.png"))); // NOI18N
        inapoi.setText("Inapoi");
        inapoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inapoiActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("Vizualizare Clienti Și Gestiune");

        actualizati.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actualizati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Update_20px.png"))); // NOI18N
        actualizati.setText("Actualizare");
        actualizati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizatiActionPerformed(evt);
            }
        });

        sterge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sterge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Delete_20px.png"))); // NOI18N
        sterge.setText("Ștergere");
        sterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stergeActionPerformed(evt);
            }
        });

        tip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inapoi)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(actualizati)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sterge))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(strada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(urmatorul)
                        .addGap(146, 146, 146))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(strada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(numar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inapoi)
                    .addComponent(actualizati)
                    .addComponent(sterge)
                    .addComponent(urmatorul)
                    .addComponent(anterior))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1284, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1302, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clientiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientiMouseClicked
        // TODO add your handling code here:
        int index=clienti.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_clientiMouseClicked

    private void urmatorulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urmatorulActionPerformed
        // TODO add your handling code here:
        pos++;

        if(pos>=getClientiList().size()){
            pos=getClientiList().size()-1;
        }
        ShowItem(pos);
    }//GEN-LAST:event_urmatorulActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        pos--;
        if(pos<0){
            pos=0;
        }
        ShowItem(pos);
    }//GEN-LAST:event_anteriorActionPerformed

    private void inapoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inapoiActionPerformed
        // TODO add your handling code here:
        this.hide();
        Meniu frm=new Meniu();
        frm.setVisible(true);
    }//GEN-LAST:event_inapoiActionPerformed

    private void actualizatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizatiActionPerformed
        // TODO add your handling code here:
        if(checkInputs()){
            String UptadeQuery=null;
            pst=null;
            pst1=null;
                try {
                    //UptadeQuery="UPDATE localizare SET CODPOSTAL=? where CODCLIENT=?";
                    //pst1=(OraclePreparedStatement) conn.prepareStatement(UptadeQuery);
                    //pst1.setString(1, postal.getText());
                    //pst1.executeUpdate();
                    
                    UptadeQuery="UPDATE client SET NUME=?, TELEFON=?, STRADA=?, NUMARUL=?, TIPCLIENT=? WHERE CODCLIENT=?";
                    pst=(OraclePreparedStatement) conn.prepareStatement(UptadeQuery);
                    pst.setString(1, nume.getText());
                    pst.setString(2, telefon.getText());
                    pst.setString(3, strada.getText());
                    pst.setString(4, numar.getText());
                    pst.setString(5, tip.getText());
                    pst.setString(6, cod.getText());
                    pst.executeUpdate();
                    Show_Products_In_JTable();
                    JOptionPane.showMessageDialog(null, "Clientul A Fost Actualizata!");
                    clearFields();
                } catch (Exception ex) {
                    Logger.getLogger(AdaugatiClienti.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
    }//GEN-LAST:event_actualizatiActionPerformed

    private void stergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stergeActionPerformed
        // TODO add your handling code here:
        if(!cod.getText().equals(""))
        {
            try {
                
                 pst1=(OraclePreparedStatement) conn.prepareStatement("DELETE FROM factura WHERE CODCLIENT=?");
                int id1=Integer.parseInt(cod.getText());
                pst1.setInt(1, id1);
                pst1.executeUpdate();
             
                
                pst=(OraclePreparedStatement) conn.prepareStatement("DELETE FROM client WHERE CODCLIENT=?");
                int id=Integer.parseInt(cod.getText());
                pst.setInt(1, id);
                pst.executeUpdate();
                Show_Products_In_JTable();
                JOptionPane.showMessageDialog(null,"Clientul a fost sters!");
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(AdaugatiClienti.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Clientul nu a fost sters!");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Clientul nu a fost sters : Nu se șterge id-ul!");
        }

    }//GEN-LAST:event_stergeActionPerformed

    private void tipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VizualizareClienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VizualizareClienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VizualizareClienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VizualizareClienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VizualizareClienti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizati;
    private javax.swing.JButton anterior;
    private javax.swing.JTable clienti;
    private javax.swing.JTextField cod;
    private javax.swing.JButton inapoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numar;
    private javax.swing.JTextField nume;
    private javax.swing.JButton sterge;
    private javax.swing.JTextField strada;
    private javax.swing.JTextField telefon;
    private javax.swing.JTextField tip;
    private javax.swing.JButton urmatorul;
    // End of variables declaration//GEN-END:variables
}
